In [1]:
import numpy as np
import pandas as pd

In [17]:
meta = pd.read_excel('C:\\Users\\Ben\\OneDrive - Duke University\\bilbo_lab\\il34_project\\il34_behavior\\il34_cohort_3_210205.xlsx', sheet_name = 'USV Schedule', header = 1)[['Pup Number', 'File legend']]

In [32]:
df = pd.read_csv('F:\\usvs\\cohort_3\\audio\\combined\\CSV\\batch_output.csv')

In [53]:
age = ['P8'] * len(df)
file_legend = df['filename'].copy()

for i in range(len(df['filename'])):
    if 'P15' in df['filename'][i]:
        age[i] = 'P15'
        file_legend[i] = '_'.join(df['filename'][i].split('_')[0:-2] + [df['filename'][i].split('_')[-1]])
        
df['age'] = age
df['file_legend'] = file_legend

In [64]:
meta['File legend'] = meta['File legend'].str.lower()
df['file_legend'] = df['file_legend'].str.lower()

In [66]:
df.set_index('file_legend').join(meta.set_index('File legend'))

,filename,num_calls,avg_duration,total_duration,freq_range,freq_band,avg_energy,age,Pup Number
ch1_a(40)_il34_01,ch1_A(40)_IL34_01,251,44.576892,11188.8,64.18,16.670279,22.225697,P8,541.0
ch1_a(40)_il34_01,ch1_A(40)_IL34_P15_01,155,37.212903,5768.0,75.12,8.544903,15.504516,P15,541.0
ch1_a(40)_il34_02,ch1_A(40)_IL34_02,345,56.811594,19600.0,67.45,21.372667,22.577594,P8,544.0
ch1_a(40)_il34_02,ch1_A(40)_IL34_P15_02,218,53.798165,11728.0,71.05,11.755550,17.501101,P15,544.0
ch1_a(40)_il34_03,ch1_A(40)_IL34_03,290,60.860690,17649.6,59.94,23.366966,26.523897,P8,546.0
...,...,...,...,...,...,...,...,...,...
ch3_a(42)_il34_03,ch3_A(42)_IL34_P15_03,2,13.600000,27.2,17.92,3.295000,12.460000,P15,570.0
ch3_a(43.5)_il34_01,ch3_A(43.5)_IL34_01,53,37.041509,1963.2,55.40,9.328113,15.630000,P8,573.0
ch3_a(43.5)_il34_01,ch3_A(43.5)_IL34_P15_01,1,22.400000,22.4,0.00,1.460000,-1.400000,P15,573.0
ch3_a(43.5)_il34_02,ch3_A(43.5)_IL34_P15_02,0,NaN,0.0,NaN,NaN,NaN,P15,NaN
ch3_a(43.5)_il34_03,ch3_A(43.5)_IL34_P15_03,0,NaN,0.0,NaN,NaN,NaN,P15,NaN